#!/bin/bash

# Call with a link to a wolfram alpha page (with or without the beginning part),
#    e.g. ./getmma /HypergeometricFunctions/Hypergeometric3F2/17/02/01/0001/
# Returns maple-readable list of Mathematica code strings + 2 link-to-page strings.

COREPATH=$1
COREPATH=${COREPATH/http:\/\//}
COREPATH=${COREPATH/functions.wolfram.com\//}

curl --silent "http://functions.wolfram.com/$COREPATH" > infile
tr -d  '\n' < infile > temp
sed -- 's/'\'CitationInfo\'\>'/\n/g' temp > infile
sed -- 's/</\n/g' infile > temp
echo '["' > temp2
grep ' == ' temp >> temp2
echo '","' >> temp2
grep 'http://functions.wolfram.com/0' temp >> temp2
echo '","' >> temp2
echo $1 >> temp2
echo '"],' >> temp2
tr -d  '\n' < temp2 > temp
sed -- 's/\/;/","/g' temp > temp2
sed -- 's/\&amp;\&amp;/","/g' temp2 > temp
grep ' == ' temp

